### PR TITLE
Fix discrepancy between value_type of map and value_type of map allocator

### PR DESCRIPTION
**Pull request by genemerewether**
To reproduce:
checkout master `8bd6a0abf9804c966659d29af160e39738f2f535` from maplab and build on Mac OS X Sierra

Mac OS X is checking that the value_type, which is `std::pair<const Key, T>`, strictly matches the allocator type, which omits the `const` in the declaration.

See the following errors:
```
In file included from /Users/mereweth/maplab_ws/src/maplab/map-structure/vi-map/src/cklam-edge.cc:2:
In file included from /Users/mereweth/maplab_ws/src/maplab/common/maplab-common/include/maplab-common/eigen-proto.h:7:
In file included from /Users/mereweth/maplab_ws/devel/include/maplab-common/eigen.pb.h:25:
In file included from /Users/mereweth/maplab_ws/devel/include/google/protobuf/extension_set.h:42:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mereweth/maplab_ws/src/maplab/common/maplab-common/include/maplab-common/temporal-buffer.h:108:16: note: in instantiation of template class 'std::__1::map<long long, backend::ResourceId, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long, backend::ResourceId> > >' requested here
      typename BufferType::const_iterator* it_lower_bound) const;

In file included from /Users/mereweth/maplab_ws/src/maplab/map-structure/vi-map/src/check-map-consistency.cc:1:
In file included from /Users/mereweth/maplab_ws/src/maplab/map-structure/vi-map/include/vi-map/check-map-consistency.h:4:
In file included from /Users/mereweth/maplab_ws/src/maplab/map-structure/posegraph/include/posegraph/vertex.h:7:
In file included from /Users/mereweth/maplab_ws/src/maplab/common/maplab-common/include/maplab-common/macros.h:6:
In file included from /Users/mereweth/maplab_ws/src/maplab/aslam_cv2/aslam_cv_common/include/aslam/common/memory.h:5:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mereweth/maplab_ws/src/maplab/common/maplab-common/include/maplab-common/temporal-buffer.h:108:16: note: in instantiation of template class 'std::__1::map<long long, backend::ResourceId, std::__1::less<long long>, std::__1::allocator<std::__1::pair<long long, backend::ResourceId> > >' requested here
      typename BufferType::const_iterator* it_lower_bound) const;
```

Fix along the same lines as:
https://github.com/MariaDB/server/pull/524/commits/dd6686462b0fa3f4d71a65c4b26cb02b65a07fec
https://github.com/percona/percona-xtrabackup/pull/469/commits/7862bd71489ce3000497f0b81254fd18b5dba1d9

by adding `const` to the explicit allocator type.

### CODE REVIEW

**Comment by mfehr** [comment]
ok to test

**Comment by genemerewether** [comment]
Sorry, a few more fixes are needed.

The reference to pointer change was in response to the linter's request to change non-const references to pointers.

Here's the weirdest one, in https://github.com/ethz-asl/maplab/blob/master/algorithms/landmark-triangulation/src/pose-interpolator.cc#L24
Seems to be conflicting with the class `IMUMeasurementBuffer`, in https://github.com/ethz-asl/maplab/blob/master/common/vio-common/include/vio-common/imu-measurements-buffer.h#L26, but I'm not sure. Anyway, deconflicting this local name and adding `const` to the allocator definition is the fix.

```
  // First add all imu measurements from this vertex to the buffer.
  typedef std::pair<const int64_t, IMUMeasurement> buffer_value_type;
  using common::TemporalBuffer;
  typedef TemporalBuffer<IMUMeasurement,
                         Eigen::aligned_allocator<buffer_value_type> >
      LTImuMeasurementBuffer;
  LTImuMeasurementBuffer imu_buffer;
```

**Comment by mfehr** [comment]
@genemerewether Thanks for fixing support on OSX! However, I'm not sure why the renaming was necessary, these two types are defined in separate namespaces (`vio_common` and `landmark_triangulation`). What was the compilation error exactly? Could you share some info about your compiler, maybe we can reproduce this?

**Comment by mfehr** [comment]
This PR has been incorporated into https://github.com/ethz-asl/maplab/pull/186, closing.

**Pull request closed without merging**
