### PR TITLE
Add deployment scripts

### PR DESCRIPTION
**Pull request by LBern**
# General
This PR introduces scripts to build a `maplab` docker image. 

## How-To

The `deploy/` folder contains a shell script to build the image.
```
./deploy/build_docker.sh
```

# Test

image

### CODE REVIEW

**Review by smauq — APPROVED** [review]
LGTM, very nice for portability. My only code comment is if you can for the sake of formatting add newlines to the end of some of the files that are missing them.

**Comment by mike-gee** [comment]
I'm not sure if dependencies are imported by script/Dockerfile.

```
Errors     << maplab_common:cmake /usr/home/ws/logs/maplab_common/build.cmake.000.log
CMake Error at /usr/home/ws/src/maplab/common/maplab-common/CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.
```

**Comment by LBern** [comment]
I have no issues running the build script. Are you just running `./deploy/build_docker.sh`?

**Comment by mike-gee** [comment]
I am just running `./deploy/build_docker.sh`.

`compile.sh` seems to fail with following error:

```
CMake Error at /usr/home/ws/src/maplab/common/maplab-common/CMakeLists.txt:4 (find_package):
  By not providing "Findcatkin_simple.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "catkin_simple", but CMake did not find one.

  Could not find a package configuration file provided by "catkin_simple"
  with any of the following names:

    catkin_simpleConfig.cmake
    catkin_simple-config.cmake

  Add the installation prefix of "catkin_simple" to CMAKE_PREFIX_PATH or set
  "catkin_simple_DIR" to a directory containing one of the above files.  If
  "catkin_simple" provides a separate development package or SDK, be sure it
  has been installed.


cd /usr/home/ws/build/maplab_common; catkin build --get-env maplab_common | catkin env -si  /usr/bin/cmake /usr/home/ws/src/maplab/common/maplab-common --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/usr/home/ws/devel -DCMAKE_INSTALL_PREFIX=/usr/home/ws/install -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fdiagnostics-color=always; cd -
```

**Pull request merged**
